### ISSUE TITLE
When a new instance is recreated, connect does not work for a while

### ISSUE THREAD

**Issue by nsorros** [ivyleavedtoadflax/remote.py#12]
When an instance is recreated, two instances appear in `remotepy list`, one with status `Terminated` and the other `Running`.

When trying to connect to the instance by name, the tool returns `Multiple instances found with name mantisnlp_gpt3`.

This is a problem we had experience with the old remote as well and can be fixed by filtering out the terminated status

**Comment by ivyleavedtoadflax** [comment]
This is resolved in #13 . Please install the latest version 0.1.7

**Comment by ivyleavedtoadflax** [comment]
Also @nsorros added you to this repo, look out for the invite.
