### ISSUE TITLE
Region needs to be specified for remote to work

### ISSUE THREAD

**Issue by nsorros** [ivyleavedtoadflax/remote.py#30]
If the region is not specified then remote throws
```
botocore.exceptions.NoRegionError: You must specify a region.
```

Ideally, the tool should be able to work without a region? Is that a thing?

**Comment by ivyleavedtoadflax** [comment]
Perhaps we could store in a config the region in which the instances exist and then pass the region to the `awscli` command. Might be a thing, but we definitely can't get rid of it completely since EC2 instances are region specific.

**Comment by nsorros** [comment]
Maybe we should mention in the README or somewhere then? If its not mentioned already. It would also be good to catch that error and print something more user friendly

**Comment by ivyleavedtoadflax** [comment]
Is this just a question of having your AWS accoutn properly configured?

**Comment by nsorros** [comment]
I suppose instances are region specific so this suggestion does not make sense on second read
